<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType Condition="'$(Configuration)' == 'Debug'">Exe</OutputType>
    <OutputType Condition="'$(Configuration)' != 'Debug'">WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <Target Name="IncrementBuildNumber" BeforeTargets="BeforeBuild">
    <ReadLinesFromFile File="build.number">
      <Output TaskParameter="Lines" ItemName="BuildNumberLines" />
    </ReadLinesFromFile>
    <PropertyGroup>
      <CurrentBuildNumber>@(BuildNumberLines)</CurrentBuildNumber>
      <NextBuildNumber>$([MSBuild]::Add($(CurrentBuildNumber), 1))</NextBuildNumber>
      <Version>0.1.12.$(NextBuildNumber)</Version>
      <AssemblyVersion>0.1.12.$(NextBuildNumber)</AssemblyVersion>
      <FileVersion>0.1.12.$(NextBuildNumber)</FileVersion>
    </PropertyGroup>
    <WriteLinesToFile File="build.number" Lines="$(NextBuildNumber)" Overwrite="true" />
  </Target>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="icon.ico" />
  </ItemGroup>
</Project>
